import type {
  User,
  Organization,
  Branch,
  Provider,
  Product,
  PurchaseOrder,
  Quote,
  Sale,
  PettyCashTransaction,
  AuditLog,
  GlobalStats,
  TenantStats,
} from '@/types';

// Current mock user (simulating logged in user)
export const mockCurrentUser: User = {
  id: 'user-1',
  email: 'admin@mitienda.com',
  name: 'Carlos Rodríguez',
  role: 'owner',
  organizationId: 'org-1',
  branchIds: ['branch-1', 'branch-2'],
  isActive: true,
  createdAt: new Date('2024-01-15'),
  lastLoginAt: new Date(),
};

export const mockSuperAdmin: User = {
  id: 'super-1',
  email: 'superadmin@gestionpro.com',
  name: 'Super Administrador',
  role: 'super_admin',
  isActive: true,
  createdAt: new Date('2023-01-01'),
  lastLoginAt: new Date(),
};

// Organizations
export const mockOrganizations: Organization[] = [
  {
    id: 'org-1',
    name: 'Mi Tienda Principal',
    slug: 'mi-tienda',
    plan: 'professional',
    status: 'active',
    ownerId: 'user-1',
    maxUsers: 10,
    maxBranches: 3,
    features: ['inventory', 'sales', 'reports', 'audit'],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'org-2',
    name: 'Ferretería El Constructor',
    slug: 'ferreteria-constructor',
    plan: 'enterprise',
    status: 'active',
    ownerId: 'user-2',
    maxUsers: 50,
    maxBranches: 10,
    features: ['inventory', 'sales', 'reports', 'audit', 'api'],
    createdAt: new Date('2023-06-20'),
  },
  {
    id: 'org-3',
    name: 'Boutique Elegance',
    slug: 'boutique-elegance',
    plan: 'starter',
    status: 'trialing',
    ownerId: 'user-3',
    maxUsers: 3,
    maxBranches: 1,
    features: ['inventory', 'sales'],
    createdAt: new Date('2024-03-01'),
    trialEndsAt: new Date('2024-03-15'),
  },
  {
    id: 'org-4',
    name: 'Distribuidora Norte',
    slug: 'distribuidora-norte',
    plan: 'professional',
    status: 'past_due',
    ownerId: 'user-4',
    maxUsers: 10,
    maxBranches: 3,
    features: ['inventory', 'sales', 'reports'],
    createdAt: new Date('2023-09-10'),
  },
];

export const mockCurrentOrganization = mockOrganizations[0];

// Branches
export const mockBranches: Branch[] = [
  {
    id: 'branch-1',
    organizationId: 'org-1',
    name: 'Sucursal Central',
    address: 'Av. Principal 123, Ciudad',
    phone: '+52 55 1234 5678',
    isMain: true,
    isActive: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'branch-2',
    organizationId: 'org-1',
    name: 'Sucursal Norte',
    address: 'Calle Norte 456, Ciudad',
    phone: '+52 55 8765 4321',
    isMain: false,
    isActive: true,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'branch-3',
    organizationId: 'org-1',
    name: 'Sucursal Sur',
    address: 'Av. Sur 789, Ciudad',
    phone: '+52 55 1111 2222',
    isMain: false,
    isActive: false,
    createdAt: new Date('2024-02-15'),
  },
];

// Users for the organization
export const mockUsers: User[] = [
  mockCurrentUser,
  {
    id: 'user-5',
    email: 'maria@mitienda.com',
    name: 'María González',
    role: 'manager',
    organizationId: 'org-1',
    branchIds: ['branch-1'],
    isActive: true,
    createdAt: new Date('2024-01-20'),
    lastLoginAt: new Date('2024-03-10'),
  },
  {
    id: 'user-6',
    email: 'juan@mitienda.com',
    name: 'Juan Pérez',
    role: 'seller',
    organizationId: 'org-1',
    branchIds: ['branch-1', 'branch-2'],
    isActive: true,
    createdAt: new Date('2024-02-01'),
    lastLoginAt: new Date('2024-03-11'),
  },
  {
    id: 'user-7',
    email: 'ana@mitienda.com',
    name: 'Ana Martínez',
    role: 'warehouse',
    organizationId: 'org-1',
    branchIds: ['branch-2'],
    isActive: true,
    createdAt: new Date('2024-02-10'),
    lastLoginAt: new Date('2024-03-09'),
  },
  {
    id: 'user-8',
    email: 'pedro@mitienda.com',
    name: 'Pedro López',
    role: 'seller',
    organizationId: 'org-1',
    branchIds: ['branch-1'],
    isActive: false,
    createdAt: new Date('2024-01-25'),
    lastLoginAt: new Date('2024-02-28'),
  },
];

// Providers
export const mockProviders: Provider[] = [
  {
    id: 'prov-1',
    organizationId: 'org-1',
    name: 'Distribuidora ABC',
    contactName: 'Roberto Sánchez',
    email: 'ventas@abc.com',
    phone: '+52 55 9999 8888',
    address: 'Zona Industrial, Nave 5',
    taxId: 'ABC123456789',
    isActive: true,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'prov-2',
    organizationId: 'org-1',
    name: 'Mayorista del Centro',
    contactName: 'Laura Jiménez',
    email: 'pedidos@mayorista.com',
    phone: '+52 55 7777 6666',
    address: 'Centro Comercial, Local 12',
    taxId: 'MAY987654321',
    isActive: true,
    createdAt: new Date('2024-01-25'),
  },
  {
    id: 'prov-3',
    organizationId: 'org-1',
    name: 'Importaciones XYZ',
    contactName: 'Miguel Torres',
    email: 'info@xyz.com',
    phone: '+52 55 5555 4444',
    isActive: false,
    createdAt: new Date('2024-02-01'),
  },
];

// Products
export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    organizationId: 'org-1',
    sku: 'ELEC-001',
    name: 'Laptop HP 15.6"',
    description: 'Laptop HP con procesador Intel i5, 8GB RAM, 256GB SSD',
    categoryId: 'cat-1',
    costPrice: 8500,
    salePrice: 12999,
    minStock: 5,
    unit: 'pieza',
    isActive: true,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'prod-2',
    organizationId: 'org-1',
    sku: 'ELEC-002',
    name: 'Mouse Inalámbrico Logitech',
    categoryId: 'cat-1',
    costPrice: 250,
    salePrice: 450,
    minStock: 20,
    unit: 'pieza',
    isActive: true,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'prod-3',
    organizationId: 'org-1',
    sku: 'ELEC-003',
    name: 'Teclado Mecánico RGB',
    categoryId: 'cat-1',
    costPrice: 800,
    salePrice: 1299,
    minStock: 10,
    unit: 'pieza',
    isActive: true,
    createdAt: new Date('2024-01-22'),
  },
  {
    id: 'prod-4',
    organizationId: 'org-1',
    sku: 'ACC-001',
    name: 'Cable HDMI 2m',
    categoryId: 'cat-2',
    costPrice: 80,
    salePrice: 150,
    minStock: 50,
    unit: 'pieza',
    isActive: true,
    createdAt: new Date('2024-01-25'),
  },
  {
    id: 'prod-5',
    organizationId: 'org-1',
    sku: 'ACC-002',
    name: 'Hub USB 4 puertos',
    categoryId: 'cat-2',
    costPrice: 180,
    salePrice: 320,
    minStock: 15,
    unit: 'pieza',
    isActive: true,
    createdAt: new Date('2024-01-25'),
  },
];

// Purchase Orders
export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-1',
    organizationId: 'org-1',
    branchId: 'branch-1',
    providerId: 'prov-1',
    orderNumber: 'OC-2024-001',
    status: 'received',
    items: [
      { id: 'poi-1', purchaseOrderId: 'po-1', productId: 'prod-1', quantity: 10, unitPrice: 8500, total: 85000 },
      { id: 'poi-2', purchaseOrderId: 'po-1', productId: 'prod-2', quantity: 50, unitPrice: 250, total: 12500 },
    ],
    subtotal: 97500,
    tax: 15600,
    total: 113100,
    createdById: 'user-1',
    createdAt: new Date('2024-02-15'),
    receivedAt: new Date('2024-02-20'),
  },
  {
    id: 'po-2',
    organizationId: 'org-1',
    branchId: 'branch-1',
    providerId: 'prov-2',
    orderNumber: 'OC-2024-002',
    status: 'pending',
    items: [
      { id: 'poi-3', purchaseOrderId: 'po-2', productId: 'prod-3', quantity: 20, unitPrice: 800, total: 16000 },
    ],
    subtotal: 16000,
    tax: 2560,
    total: 18560,
    createdById: 'user-1',
    createdAt: new Date('2024-03-05'),
  },
  {
    id: 'po-3',
    organizationId: 'org-1',
    branchId: 'branch-2',
    providerId: 'prov-1',
    orderNumber: 'OC-2024-003',
    status: 'draft',
    items: [
      { id: 'poi-4', purchaseOrderId: 'po-3', productId: 'prod-4', quantity: 100, unitPrice: 80, total: 8000 },
      { id: 'poi-5', purchaseOrderId: 'po-3', productId: 'prod-5', quantity: 30, unitPrice: 180, total: 5400 },
    ],
    subtotal: 13400,
    tax: 2144,
    total: 15544,
    createdById: 'user-5',
    createdAt: new Date('2024-03-10'),
  },
];

// Quotes
export const mockQuotes: Quote[] = [
  {
    id: 'quote-1',
    organizationId: 'org-1',
    branchId: 'branch-1',
    quoteNumber: 'COT-2024-001',
    clientName: 'Empresa Tech Solutions',
    clientEmail: 'compras@techsolutions.com',
    clientPhone: '+52 55 1234 0000',
    status: 'sent',
    items: [
      { id: 'qi-1', quoteId: 'quote-1', productId: 'prod-1', quantity: 5, unitPrice: 12999, discount: 0, total: 64995 },
      { id: 'qi-2', quoteId: 'quote-1', productId: 'prod-2', quantity: 10, unitPrice: 450, discount: 50, total: 4000 },
    ],
    subtotal: 68995,
    discount: 50,
    tax: 11039.2,
    total: 80034.2,
    validUntil: new Date('2024-03-25'),
    createdById: 'user-6',
    createdAt: new Date('2024-03-10'),
  },
  {
    id: 'quote-2',
    organizationId: 'org-1',
    branchId: 'branch-1',
    quoteNumber: 'COT-2024-002',
    clientName: 'Juan García',
    clientPhone: '+52 55 9876 5432',
    status: 'accepted',
    items: [
      { id: 'qi-3', quoteId: 'quote-2', productId: 'prod-3', quantity: 2, unitPrice: 1299, discount: 0, total: 2598 },
    ],
    subtotal: 2598,
    discount: 0,
    tax: 415.68,
    total: 3013.68,
    validUntil: new Date('2024-03-20'),
    createdById: 'user-6',
    createdAt: new Date('2024-03-08'),
  },
];

// Sales
export const mockSales: Sale[] = [
  {
    id: 'sale-1',
    organizationId: 'org-1',
    branchId: 'branch-1',
    saleNumber: 'VTA-2024-0001',
    status: 'completed',
    items: [
      { id: 'si-1', saleId: 'sale-1', productId: 'prod-1', quantity: 1, unitPrice: 12999, costPrice: 8500, discount: 0, total: 12999 },
      { id: 'si-2', saleId: 'sale-1', productId: 'prod-2', quantity: 2, unitPrice: 450, costPrice: 250, discount: 0, total: 900 },
    ],
    subtotal: 13899,
    discount: 0,
    tax: 2223.84,
    total: 16122.84,
    paymentMethod: 'card',
    clientName: 'Cliente Mostrador',
    createdById: 'user-6',
    createdAt: new Date('2024-03-11T10:30:00'),
  },
  {
    id: 'sale-2',
    organizationId: 'org-1',
    branchId: 'branch-1',
    saleNumber: 'VTA-2024-0002',
    status: 'completed',
    items: [
      { id: 'si-3', saleId: 'sale-2', productId: 'prod-4', quantity: 3, unitPrice: 150, costPrice: 80, discount: 0, total: 450 },
    ],
    subtotal: 450,
    discount: 0,
    tax: 72,
    total: 522,
    paymentMethod: 'cash',
    createdById: 'user-6',
    createdAt: new Date('2024-03-11T11:15:00'),
  },
  {
    id: 'sale-3',
    organizationId: 'org-1',
    branchId: 'branch-2',
    saleNumber: 'VTA-2024-0003',
    status: 'completed',
    items: [
      { id: 'si-4', saleId: 'sale-3', productId: 'prod-3', quantity: 1, unitPrice: 1299, costPrice: 800, discount: 100, total: 1199 },
      { id: 'si-5', saleId: 'sale-3', productId: 'prod-5', quantity: 2, unitPrice: 320, costPrice: 180, discount: 0, total: 640 },
    ],
    subtotal: 1839,
    discount: 100,
    tax: 278.24,
    total: 2117.24,
    paymentMethod: 'transfer',
    clientName: 'Oficina Central S.A.',
    createdById: 'user-7',
    createdAt: new Date('2024-03-11T14:00:00'),
  },
];

// Petty Cash Transactions
export const mockPettyCashTransactions: PettyCashTransaction[] = [
  {
    id: 'pct-1',
    organizationId: 'org-1',
    branchId: 'branch-1',
    type: 'income',
    amount: 5000,
    category: 'Fondo Inicial',
    description: 'Apertura de caja chica del mes',
    createdById: 'user-1',
    createdAt: new Date('2024-03-01T09:00:00'),
  },
  {
    id: 'pct-2',
    organizationId: 'org-1',
    branchId: 'branch-1',
    type: 'expense',
    amount: 250,
    category: 'Papelería',
    description: 'Compra de hojas y toner para impresora',
    reference: 'FAC-12345',
    createdById: 'user-5',
    createdAt: new Date('2024-03-05T11:30:00'),
  },
  {
    id: 'pct-3',
    organizationId: 'org-1',
    branchId: 'branch-1',
    type: 'expense',
    amount: 180,
    category: 'Limpieza',
    description: 'Artículos de limpieza',
    createdById: 'user-5',
    createdAt: new Date('2024-03-07T10:00:00'),
  },
  {
    id: 'pct-4',
    organizationId: 'org-1',
    branchId: 'branch-1',
    type: 'expense',
    amount: 500,
    category: 'Transporte',
    description: 'Envío de mercancía a cliente',
    reference: 'GUIA-98765',
    createdById: 'user-6',
    createdAt: new Date('2024-03-10T15:00:00'),
  },
  {
    id: 'pct-5',
    organizationId: 'org-1',
    branchId: 'branch-1',
    type: 'income',
    amount: 2000,
    category: 'Reposición',
    description: 'Reposición de fondo de caja',
    createdById: 'user-1',
    createdAt: new Date('2024-03-11T09:00:00'),
  },
];

// Audit Logs
export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit-1',
    organizationId: 'org-1',
    branchId: 'branch-1',
    userId: 'user-1',
    action: 'login',
    entity: 'session',
    entityId: 'session-123',
    createdAt: new Date('2024-03-11T08:00:00'),
  },
  {
    id: 'audit-2',
    organizationId: 'org-1',
    branchId: 'branch-1',
    userId: 'user-1',
    action: 'price_change',
    entity: 'product',
    entityId: 'prod-1',
    oldValue: { salePrice: 11999 },
    newValue: { salePrice: 12999 },
    createdAt: new Date('2024-03-11T09:30:00'),
  },
  {
    id: 'audit-3',
    organizationId: 'org-1',
    branchId: 'branch-1',
    userId: 'user-6',
    action: 'sale',
    entity: 'sale',
    entityId: 'sale-1',
    newValue: { total: 16122.84, items: 2 },
    createdAt: new Date('2024-03-11T10:30:00'),
  },
  {
    id: 'audit-4',
    organizationId: 'org-1',
    branchId: 'branch-1',
    userId: 'user-5',
    action: 'stock_change',
    entity: 'inventory',
    entityId: 'inv-1',
    oldValue: { quantity: 15 },
    newValue: { quantity: 25 },
    createdAt: new Date('2024-03-11T11:00:00'),
  },
  {
    id: 'audit-5',
    organizationId: 'org-1',
    branchId: 'branch-1',
    userId: 'user-1',
    action: 'create',
    entity: 'user',
    entityId: 'user-8',
    newValue: { email: 'nuevo@mitienda.com', role: 'seller' },
    createdAt: new Date('2024-03-11T14:00:00'),
  },
];

// Global Stats (for Super Admin)
export const mockGlobalStats: GlobalStats = {
  totalOrganizations: 156,
  activeOrganizations: 142,
  totalUsers: 1250,
  activeUsers: 890,
  mrr: 125000,
  arr: 1500000,
  churnRate: 2.5,
  growthRate: 15.3,
};

// Tenant Stats
export const mockTenantStats: TenantStats = {
  totalSales: 1523,
  totalRevenue: 2850000,
  totalProducts: 450,
  lowStockProducts: 12,
  pendingOrders: 5,
  todaySales: 18,
  todayRevenue: 45680,
  monthlyRevenue: 285000,
};

// Chart Data
export const mockRevenueChartData = [
  { month: 'Ene', ingresos: 186000, gastos: 80000 },
  { month: 'Feb', ingresos: 205000, gastos: 95000 },
  { month: 'Mar', ingresos: 237000, gastos: 110000 },
  { month: 'Abr', ingresos: 273000, gastos: 120000 },
  { month: 'May', ingresos: 209000, gastos: 100000 },
  { month: 'Jun', ingresos: 214000, gastos: 105000 },
];

export const mockSalesChartData = [
  { day: 'Lun', ventas: 42 },
  { day: 'Mar', ventas: 38 },
  { day: 'Mié', ventas: 55 },
  { day: 'Jue', ventas: 47 },
  { day: 'Vie', ventas: 62 },
  { day: 'Sáb', ventas: 78 },
  { day: 'Dom', ventas: 35 },
];

export const mockCategoryDistribution = [
  { categoria: 'Electrónicos', valor: 45, fill: 'var(--color-chart-1)' },
  { categoria: 'Accesorios', valor: 25, fill: 'var(--color-chart-2)' },
  { categoria: 'Cables', valor: 15, fill: 'var(--color-chart-3)' },
  { categoria: 'Software', valor: 10, fill: 'var(--color-chart-4)' },
  { categoria: 'Otros', valor: 5, fill: 'var(--color-chart-5)' },
];

export const mockOrganizationGrowth = [
  { month: 'Ene', nuevas: 12, canceladas: 2 },
  { month: 'Feb', nuevas: 18, canceladas: 3 },
  { month: 'Mar', nuevas: 15, canceladas: 1 },
  { month: 'Abr', nuevas: 22, canceladas: 4 },
  { month: 'May', nuevas: 28, canceladas: 2 },
  { month: 'Jun', nuevas: 25, canceladas: 3 },
];

export const mockPlanDistribution = [
  { plan: 'Starter', cantidad: 65, fill: 'var(--color-chart-3)' },
  { plan: 'Professional', cantidad: 72, fill: 'var(--color-chart-1)' },
  { plan: 'Enterprise', cantidad: 19, fill: 'var(--color-chart-2)' },
];
